// <auto-generated />
using System;
using ColorRegressionApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColorRegressionApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526175638_MakePredictionModelIdNullable")]
    partial class MakePredictionModelIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("ColorRegressionApp.Models.ExperimentPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("A")
                        .HasColumnType("REAL");

                    b.Property<double>("B")
                        .HasColumnType("REAL");

                    b.Property<double>("L")
                        .HasColumnType("REAL");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X1")
                        .HasColumnType("REAL");

                    b.Property<double>("X2")
                        .HasColumnType("REAL");

                    b.Property<double>("X3")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ExperimentPoints");
                });

            modelBuilder.Entity("ColorRegressionApp.Models.ModelCoefficient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("B1")
                        .HasColumnType("REAL");

                    b.Property<double>("B2")
                        .HasColumnType("REAL");

                    b.Property<double>("B3")
                        .HasColumnType("REAL");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelCoefficients");
                });

            modelBuilder.Entity("ColorRegressionApp.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ResultX1")
                        .HasColumnType("REAL");

                    b.Property<double>("ResultX2")
                        .HasColumnType("REAL");

                    b.Property<double>("ResultX3")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetA")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetB")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetL")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("ColorRegressionApp.Models.RegressionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RegressionModels");
                });

            modelBuilder.Entity("ColorRegressionApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
